# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v4

  #     # Runs a single command using the runners shell
  #     - name: Run a one-line script
  #       run: echo Hello, world!

  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout Code
    #     uses: actions/checkout@v3
    #   - name: Run Gitleaks
    #     uses: docker://zricethezav/gitleaks
    #     with:
    #       args: detect -s /repo --report-path /repo/my_report.json

    #   - name: Upload Gitleaks Report
    #     uses: actions/upload-artifact@v3
    #     with:
    #       name: gitleaks-report
    #       path: my_report.json


    steps:
      - name: Run Gitleaks
        uses: docker://zricethezav/gitleaks
        with:
         args: -c "git clone https://github.com/$GITHUB_REPOSITORY.git /repo && gitleaks detect"

      - name: Upload Gitleaks Report
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: my_report.json
